package com.calsoft.pos.model.category;

import lombok.Data;

@Data
public class Category {

	public final static int ALLCHILDREN_ATTRIBUTE_ID = 54;
	public final static int AVAILABLESORTBY_ATTRIBUTE_ID = 65;
	public final static int CATEGORYSEONAME_ATTRIBUTE_ID = 323;
	public final static int CHILDREN_ATTRIBUTE_ID = 56;
	public final static int CHILDRENCOUNT_ATTRIBUTE_ID = 64;
	public final static int CREARESEOHEADING_ATTRIBUTE_ID = 268;
	public final static int CUSTOMAPPLYTOPRODUCTS_ATTRIBUTE_ID = 69;
	public final static int CUSTOMDESIGN_ATTRIBUTE_ID = 58;
	public final static int CUSTOMDESIGNFROM_ATTRIBUTE_ID = 59;
	public final static int CUSTOMDESIGNTO_ATTRIBUTE_ID = 60;
	public final static int CUSTOMLAYOUTUPDATE_ATTRIBUTE_ID = 62;
	public final static int CUSTOMUSEPARENTSETTINGS_ATTRIBUTE_ID = 68;
	public final static int DEFAULTSORTBY_ATTRIBUTE_ID = 66;
	public final static int DESCRIPTION_ATTRIBUTE_ID = 44;
	public final static int DISPLAYMODE_ATTRIBUTE_ID = 49;	
	public final static int EXCLUDEFROMCROSSLINKING_ATTRIBUTE_ID = 318;
	public final static int EXCLUDEFROMHTMLSITEMAP_ATTRIBUTE_ID = 328;
	public final static int EXCLUDEFROMSITEMAP_ATTRIBUTE_ID = 325;
	public final static int FILTERPRICERANGE_ATTRIBUTE_ID = 70;
	public final static int IMAGE_ATTRIBUTE_ID = 45;
	public final static int INCLUDEINMENU_ATTRIBUTE_ID = 67;
	public final static int ISACTIVE_ATTRIBUTE_ID = 42;
	public final static int ISANCHOR_ATTRIBUTE_ID = 51;
	public final static int LANDINGPAGE_ATTRIBUTE_ID = 50;
	public final static int LEVEL_ATTRIBUTE_ID = 63;
	public final static int METADESCRIPTION_ATTRIBUTE_ID = 48;
	public final static int METAKEYWORDS_ATTRIBUTE_ID = 47;
	public final static int METAROBOTS_ATTRIBUTE_ID = 316;
	public final static int METATITLE_ATTRIBUTE_ID = 46;
	public final static int NAME_ATTRIBUTE_ID = 41;
	public final static int PAGELAYOUT_ATTRIBUTE_ID = 61;
	public final static int PATH_ATTRIBUTE_ID = 52;
	public final static int PATHINSTORE_ATTRIBUTE_ID = 55;
	public final static int POSITION_ATTRIBUTE_ID = 53;
	public final static int REDIRECTPRIORITY_ATTRIBUTE_ID = 319;
	public final static int THUMBNAIL_ATTRIBUTE_ID = 132;
	public final static int URLKEY_ATTRIBUTE_ID = 43;
	public final static int URLPATH_ATTRIBUTE_ID = 57;
	public final static int PRODUCT_LIST_TYPE_ATTRIBUTE_ID = 384;
	public final static int DISPLAY_DESCRIPTION_ATTRIBUTE_ID = 386;

	// STORE ID
	public final static int ALLCHILDREN_STORE_ID = 0;
	public final static int AVAILABLESORTBY_STORE_ID = 0;
	public final static int CATEGORYSEONAME_STORE_ID = 0;
	public final static int CHILDREN_STORE_ID = 1;
	public final static int CREARESEOHEADING_STORE_ID = 0;
	public final static int CUSTOMAPPLYTOPRODUCTS_STORE_ID = 0;
	public final static int CUSTOMDESIGN_STORE_ID = 1;
	public final static int CUSTOMDESIGNFROM_STORE_ID = 0;
	public final static int CUSTOMLAYOUTUPDATE_STORE_ID = 0;
	public final static int CUSTOMUSEPARENTSETTINGS_STORE_ID = 0;
	public final static int DEFAULTSORTBY_STORE_ID = 0;
	public final static int DESCRIPTION_STORE_ID = 0;
	public final static int DISPLAYMODE_STORE_ID = 0;
	public final static int EXCLUDEFROMCROSSLINKING_STORE_ID = 0;
	public final static int EXCLUDEFROMHTMLSITEMAP_STORE_ID = 0;
	public final static int EXCLUDEFROMSITEMAP_STORE_ID = 0;
	public final static int FASHIONCATEGORY_STORE_ID = 1;
	public final static int FILTERPRICERANGE_STORE_ID = 0;
	public final static int IMAGE_STORE_ID = 0;
	public final static int INCLUDEINMENU_STORE_ID = 0;
	public final static int ISACTIVE_STORE_ID = 0;
	public final static int ISANCHOR_STORE_ID = 0;
	public final static int LANDINGPAGE_STORE_ID = 0;
	public final static int METADESCRIPTION_STORE_ID = 0;
	public final static int METAKEYWORDS_STORE_ID = 0;
	public final static int METAROBOTS_STORE_ID = 0;
	public final static int METATITLE_STORE_ID = 0;
	public final static int NAME_STORE_ID = 0;
	public final static int PAGELAYOUT_STORE_ID = 0;
	public final static int PATHINSTORE_STORE_ID = 1;
	public final static int REDIRECTPRIORITY_STORE_ID = 0;
	public final static int THUMBNAIL_STORE_ID = 1;
	public final static int URLKEY_STORE_ID = 0;
	public final static int URLPATH_STORE_ID = 0;

	public final static int CHILDRENCOUNT_STORE_ID = 0;
	public final static int PATH_STORE_ID = 1;
	public final static int LEVEL_STORE_ID = 1;
	public final static int POSITION_STORE_ID = 1;
	public final static int PRODUCT_LIST_TYPE_STORE_ID = 0;
	public final static int DISPLAY_DESCRIPTION_STORE_ID = 0;

	public final static int CUSTOMDESIGNTO_STORE_ID = 1;

	private int categoryId = -1;
	private int parentId;
	private String allChildren;
	private String availableSortBy;
	private String categorySeoName;
	private String children;
	private String creareseoHeading;
	private String customapplyToProducts;
	private String customDesign;
	private String customDesignFrom;
	private String customDesignTo;
	private String customLayoutUpdate;
	private String customUseParentSettings;
	private String defaultSortBy;
	private String description;
	private String displayMode;
	private String excludeFromCrosslinking;
	private String excludeFromHtmlSitemap;
	private String excludeFromSitemap;
	private String fashionCategory;
	private String filterPriceRange;
	private String image;
	private String includeInMenu;
	private String isActive;
	private String isAnchor;
	private String landingPage;
	private String metaDescription;
	private String MetaKeywords;
	private String MetaRobots;
	private String metaTitle;
	private String categoryName;
	private String PageLayout;
	private String path;
	private String pathInStore;
	private String redirectPriority;
	private String Thumbnail;
	private String URLKey;
	private String urlPath;
	private int position;
	private int level;
	private int childrenCount;
	private String operationType;
	private int activeCheck;
	private String productListType;
	private String displayDescription;

}
